# Generated by Django 5.1.4 on 2025-01-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
