# Generated by Django 5.1.4 on 2025-01-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_finder', '0002_event_link_venue_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='venue_id',
        ),
    ]
